### ISSUE TITLE
Affiliated universities

### ISSUE THREAD

**Issue by paolo-tonella** [phdfbk/phdfbk.github.io#1]
Sarebbe importante indicare sotto ogni affiliated university se si tratta di joint school o agreement:

JOINT PHD SCHOOL
University of Bologna
University of Padova
University of Genova
Consortium of the Universities of Firenze-Pisa-Siena

AGREEMENT WITH PHD SCHOOL
University of Trento
University College London, UK
Imperial College London, UK
Queen Mary University, London, UK
Massachusetts Institute of Technology, USA
University of Glasgow, UK

**Comment by napo** [comment]
ho inserito il tag
kindcontract
(possiamo anche cambiare il nome)
nel file markdown delle affiliazioni

Vedi come esempio
https://github.com/phdfbk/phdfbk.github.io/blob/master/affiliations/_posts/2014-07-17-universitapadova-aff2.markdown

Nella visualizzazione avviene sotto il nome dell'università nella sezione "network"

Riesci a produrre i file markdown per le altre università?

**Comment by paolo-tonella** [comment]
Direi che va bene. Ci penso io a inserire le altre università. Puoi chiudere l'issue.

**Comment by napo** [comment]
Ho aggiungo anche l'informazione nella finestra modale dell'universita'.
