### ISSUE TITLE
Handle number of open calls = zero

### ISSUE THREAD

**Issue by paolo-tonella** [phdfbk/phdfbk.github.io#10]
Ci potrebbero essere dei periodi dell'anno in cui non ci sono open call. In tal caso, la pagina dovrebbe mostrare una scritta tipo: "There are currently no open calls. New open calls will be announced in this page as soon as they are available."

**Comment by napo** [comment]
Ho inserito la condizione che fa questo controllo.
Credo pero' si possa fare meglio senza doverlo specificare nel markdown ma calcolandolo sulla base dei post con le offerte.

**Comment by paolo-tonella** [comment]
Ho provato a togliere l'unica call aperta, ed e' apparsa una pagina vuota, senza alcuna scritta esplicativa.

**Comment by napo** [comment]
Come la hai levata?
In teoria se diventa "position: 0" dovrebbe comparire la frase

"There are currently no open calls. New open calls will be announced in this page as soon as they are available."

INFO: http://blablabla...

La gestione e' alla riga 21 di opencalls_grid.html

https://github.com/phdfbk/phdfbk.github.io/blob/master/_includes/opencalls_grid.html#L21

**Comment by paolo-tonella** [comment]
Ho rimosso i file markdown - ho visto che github rimuove tutta la cartella opencalls/_posts. Provo a mettere position = 0; se funziona, direi che va bene.

**Comment by paolo-tonella** [comment]
Ho messo number_of_positions: 0 in 2016-06-01-uni_trento.markdown, ma oltre a visualizzare la frase concordata continuava a far vedere la posizione linciata dal tag uni_trento_call. Allora nel file 2016-06-01-trento-call1.markdown ho sostituito uni_trento_call con uni_trento_call_NULL. Questo ha fatto sparire le info sulla posizione specifica, ma ha lasciato varie informazioni che non dovrebbero essere visualizzate (vedi immagine allegata):

JOINT CALL WITH UNIVERSITY OF TRENTO
Topic: Information and Communication Technologies
Info: http://ict.unitn.it/application...
Closing date: 5 sept 2016

Tutte queste informazioni dovrebbero sparire e l'unica scritta visibile dovrebbe essere:

There are currently no open calls. New open calls will be announced in this page as soon as they are available.

![screen shot 2016-08-18 at 09 11 33](https://cloud.githubusercontent.com/assets/20944900/17765183/8b53acb2-6524-11e6-9f90-7005602214e5.png)

**Comment by napo** [comment]
ma vuoi che sparisca anche "Topic: ..." ?

**Comment by paolo-tonella** [comment]
La scritta dovrebbe apparire solo se non c'e' alcuna open call con nessuna università' e su nessun topic. Vorrei evitare una visualizzazione del tipo:
- JOINT CALL WITH UNITN  - no open calls
- JOINT CALL WITH UNIGE  - no open calls
- JOINT CALL WITH UNIBO  - no open calls
- JOINT CALL WITH UNIFI-PI-SI  - no open calls
- JOINT CALL WITH UCL  - topic:..., info: ..., closing date: ..., etc.

Perche' cosi' uno dovrebbe fare scroll su una serie di "no open calls" prima di trovare l'info interessante (le call aperte; nell'esempio qui sopra, UCL).

Ovvero, toglierei le call scadute (cancellando i file) e se non ne rimane nessuna, a video farei apparire solo la scritta "no open calls...", senza riferimento ad alcuna università e topic.

**Comment by napo** [comment]
Ok
ho gestito in maniera completamente diversa il tutto:
se non ci sono call aperte (= non ci sono file) compare il messaggio 

## There are currently no open calls.

**New open calls will be announced in this page as soon as they are available.**

https://github.com/phdfbk/phdfbk.github.io/commit/6ac8ce1437cba2462dae2b70c4c5105080a81a07

Per il numero di posizioni aperte non vado più a leggere la variabile di quante ce ne sono aperte, ma leggo il numero di file che corrispondono a tag associato alla call (= possiamo levare la variabile "positions")
