### ISSUE TITLE
Modal view of universities

### ISSUE THREAD

**Issue by paolo-tonella** [phdfbk/phdfbk.github.io#11]
Ho notato che "reference person" nella modal view di ciascuna università e' poco utile (e spesso difficile da reperire), mentre sarebbe più utile un link che punti alla "doctoral school". Ad esempio, per UNITN / DISI, un link a: http://ict.unitn.it.

**Comment by napo** [comment]
Mi sembra che con @gaetanocalabrese eravamo d'accordo di mettere in evidenza le persone con cui si collabora.
In ogni caso nessun problema a cambiare l'informazione.
Io sono anche dell'idea che servono i link alle pagine dei referenti (se vogliamo lasciarli)
Nota che possiamo anche definire la moda view in altro modo.
Vedo se levare il campo qualora il valore sia vuoto

**Comment by paolo-tonella** [comment]
OK, lasciamo i referenti, ma visualizziamoli solo se indicati; aggiungiamo pero' il campo doctoral school

**Comment by paolo-tonella** [comment]
Il dipartimento dovrebbe essere cliccabile; inoltre, la reference person e' di solito il direttore della scuola di dottorato, quindi non e' molto significativa per gli studenti che accedono al sito: non dice molto sulla ricerca fatta in collaborazione. Per questo secondo me sarebbe meglio sostituire "Reference person" con "Doctoral school", rendendo quest'ultima cliccabile. 

Ad esempio, a Firenze-Pisa-Siena il referente e' Paolo Frasconi, ma la ricerca si fa con molti altri ricercatori (ad es. Marco Gori a Siena). Invece la scuola di dottorato in Smart Computing (http://smartcomputing.unifi.it/index.html) e' molto più' significativa.

**Comment by napo** [comment]
Ho risolto la questione dipartimento con il clic.
In merito alla reference person, dimmi tu come agire.
Nei file abbiamo la voce "reference person" 
Se mi dici che abbiamo l'url della scuola di dottorato, allora mettiamo quella.
Nei file basta cambiare il valore assegnato a "reference person" con quello dell'url della scuola di dottorato.
Meglio pero' se scriviamo una cosa tipo
"phdschool" e associamo l'indirizzo.
A quel punto servono due modifiche:
- una alla riga 36
  https://github.com/phdfbk/phdfbk.github.io/blob/master/_includes/affiliation_modals.html#L36
  dove "reference_person" diventa "phdschoo"
- una alla riga 28
  https://github.com/phdfbk/phdfbk.github.io/blob/master/_includes/affiliation_modals.html#L28
  dove "Reference person" diventa "PhD School"

**Comment by paolo-tonella** [comment]
Ho aggiunto l'attributo phdschool ad alcuni dipartimenti (quelli UNITN). A breve lo aggiungo anche a tutti gli altri, delle altre università'. Puoi intanto visualizzarlo al posto di reference person, cosi' vediamo come si presenta?

**Comment by napo** [comment]
prova
ps: non mi piacciono i link con l'underline

**Comment by paolo-tonella** [comment]
Sono d'accordo. Inoltre mi sembra brutto visualizzare l'URL. Ti proporrei di sdoppiare l'attributo in:

phdschool: nome della scuola di PhD
phdschoollink: URL che porta alla scuola

Visualizzerei il primo, rendendolo cliccabile in modo che porti al secondo. Se sei d'accordo, faccio il cambio su tutte le università' affiliate.

Inoltre ho notato che il link alla phd school al momento non funziona (porta alla landing page di phd.fbk.eu).

**Comment by paolo-tonella** [comment]
Meglio phdschool_link, più' leggibile.

**Comment by paolo-tonella** [comment]
Ho pensato a una soluzione ancora più' semplice: teniamo solo l'attributo phdschool e lo inseriamo come hyperlink:

phdschool: <a href="http://ict.unitn.it/">Information and Communication Technologies</a>

Che ne dici?

**Comment by napo** [comment]
preferirei tenere separato l'html dalla rappresentazione.
Tra l'altro se vuoi che la pagina si apra in un nuovo tab devi cambiare il codice aggiungendo anche _target="_new".._

es.

``` html
<a href="http://web.unitn.it/en/drbs" target="_new">Biomolecular Sciences</a>
```

Ora ho sistemato la vista

**Comment by paolo-tonella** [comment]
OK, allora ripristino l'attributo phdschool_link.

**Comment by napo** [comment]
sistemato
