### ISSUE TITLE
Visualizzazione dipartimenti multipli

### ISSUE THREAD

**Issue by paolo-tonella** [phdfbk/phdfbk.github.io#12]
Si e' corrotta la visualizzazione di dipartimenti multipli, che prima funzionava. Ora viene fatta come bullet point innestati (vedi screenshot allegato, ottenuto per UNITN).

![screen shot 2016-08-16 at 16 52 21](https://cloud.githubusercontent.com/assets/20944900/17703391/d562231e-63d1-11e6-94c8-3365b0d486d3.png)

**Comment by napo** [comment]
stavo lavorando su una nuova visualizzazione
Per ora ho lasciato tutto come prima
