### ISSUE TITLE
Website not visualised in open calls

### ISSUE THREAD

**Issue by paolo-tonella** [phdfbk/phdfbk.github.io#13]
Il link Website nella open call attuale non viene visualizzato

**Comment by napo** [comment]
Risolto
... tutta colpa di una T fuori posto :)

**Comment by paolo-tonella** [comment]
Adesso non solo non visualizza il link, ma e' scomparso anche l'attributo Website (vedi immagine allegata).
![screen shot 2016-08-17 at 08 45 32](https://cloud.githubusercontent.com/assets/20944900/17727062/fc4d1508-6456-11e6-99fe-3ea879a8e9be.png)

**Comment by napo** [comment]
Ops!
Grazie della segnalazione.
Lo avevo escluso con una "if" legata al numero di posizioni
