### ISSUE TITLE
Missing newlines in modal view of universities

### ISSUE THREAD

**Issue by paolo-tonella** [phdfbk/phdfbk.github.io#14]
Sono saltati gli a-capo nella modal view delle università'. Vedi UNITN, immagine allegata, in cui Reference person dovrebbe essere elencata sotto al dipartimento, ora appare prima del dipartimento successivo (che e' quello sbagliato).

![screen shot 2016-08-17 at 08 49 42](https://cloud.githubusercontent.com/assets/20944900/17727126/921b22b4-6457-11e6-9fe1-9ac644959ea4.png)

**Comment by napo** [comment]
ho cambiato tutto mettendo una tabella.
Dimmi se ti va bene e/o se vuoi che cambio i colori.
PS: la parte di contact e' da sistemare.
