### ISSUE TITLE
Add abstract to student's modal view

### ISSUE THREAD

**Issue by paolo-tonella** [phdfbk/phdfbk.github.io#17]
Aggiungere un abstract di ricerca, da visualizzare tra “advisor” e “more information”, dove attualmente compare uno spazio bianco. Modificare il foglio G-doc gestito da Patrizia aggiungendo la colonna abstract.

**Comment by napo** [comment]
Sul foglio usato da Patrizia c'è un campo dal nome subtitle non usato
Sarei per cambiare il nome della colonna in abstract

Se vuoi aggiungere campi fallo sulla destra

**Comment by paolo-tonella** [comment]
Ho rinominato subtitle in abstract nel G-doc.

**Comment by napo** [comment]
Al momento fra "advisor" e "more information" e' presente il campo "about me"
Solo che non abbiamo testi e quindi non viene fuori nulla.

Io sarei per avere delle frasi in prima persona che evidenziano qualcosa del profilo della persona e poi del perche' ha scelto il phd.

A questo punto per la parte di abstract ho bisogno di sapere:
1. come va introdotto
Es "The abstract of my research is "
2. dove va messo

**Comment by paolo-tonella** [comment]
Mi ero dimenticato del campo "about me". Sono d'accordo con la tua proposta di evidenziare profilo e motivazioni in questo campo. Terrei pero' comunque l'abstract, da visualizzare subito dopo "about me", introducendolo con "Here is an abstract of my research: ". Penso infatti che per i candidati studenti sia interessante, oltre a sapere qualcosa sugli studenti attuali e sulle loro motivazioni, vedere anche degli esempi di abstract di ciò su cui si fa ricerca. Inoltre non e' detto che tutti riempiano il campo "about me" e molti potrebbero fornire poche informazioni in questo campo, quindi avere anche l'abstract scientifico e' secondo me utile.

**Comment by napo** [comment]
Ok 
dove lo piazzio?
In realta' lo avevo gia' messo con la frase "The abstract of my research is:" 
ora pero' lo ho modificato in 
"Here an abstrsact of my research"
come vedi qui
https://github.com/phdfbk/phdfbk.github.io/commit/9df9648a119e9de412501c91aa10f41005655296

Attualmente l'ordine e' 
1. I'm a student of the  _{{ university }}_
2. I come from  _{{ from }}_
3. My research is on _{{ research_topic }}_
4. The advisor is  _{{ advisor }}_
5. Here is an abstract of my research: _{{ abstract }}_
6. Something about me _{{ aboutme }}_
7. more information _{{ website }}_
8. You can contact me by email _{{ email }}_

I testi dal 1 al 5 compaiono a destra della foto
Quelli dal 6 al 8 invece sotto

nota:
nel csv le email sono complete di "@", via web sostituisco la stringa con una icona
(per avere un minimo di spam protection)

**Comment by paolo-tonella** [comment]
Si potrebbero scambiare 5 e 6, in modo da mettere prima le info personali e poi l'abstract.

**Comment by napo** [comment]
Avevo pensato alla parte alta come una scheda "fredda" e quella bassa più divulgativa
In ogni caso basta invertire i due blocchi nel codice student_modals.html

**Comment by paolo-tonella** [comment]
OK, condivido la logica: allora teniamo il tuo ordinamento, ovvero, abstract nella parte alta e about me in quella personale, bassa.
