### ISSUE TITLE
Remove subtitle in student modal view

### ISSUE THREAD

**Issue by paolo-tonella** [phdfbk/phdfbk.github.io#18]
Il campo subtitle si puo’ eliminare, in quanto il titolo della tesi e’ noto solo alla fine.

**Comment by napo** [comment]
Done

PS:
Eliminiamo la voce anche nel foglio di calcolo e di conseguenza nello script e nei file .md?

**Comment by napo** [comment]
ignorare il "PS" in quanto e' stato risolto nella issue #17
