### ISSUE TITLE
Icona Laboratories

### ISSUE THREAD

**Issue by paolo-tonella** [phdfbk/phdfbk.github.io#2]
In WHAT metterei un icona per Laboratories che ricordi i laboratori (es. un’ampolla) al posto dell'icona attuale (cappello laurea) -- vedi immagine.

Lascerei invece la scritta WHAT in <h4>

![screen shot 2016-08-13 at 13 44 18](https://cloud.githubusercontent.com/assets/20944900/17642969/3493def4-615c-11e6-8a21-c2cae4216012.png)

**Comment by napo** [comment]
Risolto
https://github.com/phdfbk/phdfbk.github.io/commit/85604344fd6545b0f0f56fb0e3e0830c89b18fe3
