### ISSUE TITLE
thumb images

### ISSUE THREAD

**Issue by napo** [phdfbk/phdfbk.github.io#23]
dato che nel codice non facciamo uso di thumb images, propongo di cancellare tutte le immagini *thumb.jpg dal repository
@gaetanocalabrese e @paolo-tonella cosa ne pensate?

**Comment by paolo-tonella** [comment]
Si', certo: mi chiedevo a cosa servissero...

**Comment by napo** [comment]
fatto :)
https://github.com/phdfbk/phdfbk.github.io/commit/710e4f3a30b9b2707f3cdfad00bade82e7004c44
