### ISSUE TITLE
Alumni, link "all"

### ISSUE THREAD

**Issue by paolo-tonella** [phdfbk/phdfbk.github.io#28]
Il link "all" include una tabella di dati vuota in testa (vedi immagine allegata).
![screen shot 2016-09-05 at 17 11 51](https://cloud.githubusercontent.com/assets/20944900/18251867/04f290ea-738c-11e6-9b78-fd324e0ebf64.png)

**Comment by gaetanocalabrese** [comment]
Sistemato, messo un controllo sul gruppo con anno nullo...

Ho istallato python 2.7 , ho ripreso gli script di Maurizio per la
generazione degli students e creato quella per gli alumni, ora funzionano
entrambi leggono dal foglio google

Gaetano
