### ISSUE TITLE
Griglia studenti

### ISSUE THREAD

**Issue by paolo-tonella** [phdfbk/phdfbk.github.io#3]
Nella griglia degli studenti, le righe si spezzano in modo strano (vedi immagine allegata).

![screen shot 2016-08-13 at 10 27 31](https://cloud.githubusercontent.com/assets/20944900/17642924/65c765e2-615a-11e6-98a7-db46dd9ee7ae.png)

**Comment by napo** [comment]
ho cambiato il sistema di griglia usato dal template.
Adesso gli studenti appaiono su sei colonne, ridimensionando lo schermo scendono a 4 e poi a 1 (per gli smartphone)
Fa un po' di test (meglio se con browser e risoluzioni diversi) che poi (se va bene) chiudiamo il ticket.

PS: ho aggiunto una linea orizzontale di separazione su ogni colonna come "debug" ma dato che mi sembrava "carina" la ho lasciata.
Se vogliamo levarla ... avvisa :)

**Comment by paolo-tonella** [comment]
Sia su PC che su smartphone, mi sembra che funzioni tutto bene. Puoi chiudere l'issue.

**Comment by napo** [comment]
alla fine ho cambiato pure questa

**Comment by paolo-tonella** [comment]
La nuova griglia studenti mi piace; farei in modo che quando ci sono campi vuoti (es. "more information" vuoto), il titolo del campo non venga visualizzato.

**Comment by napo** [comment]
sistemata anche la parte dei campi vuoti
https://github.com/phdfbk/phdfbk.github.io/commit/c8552b194a3e057aa1e10cc0408a869677bb996f
