### ISSUE TITLE
Prevedere una immagine di default quando manca la foto

### ISSUE THREAD

**Issue by paolo-tonella** [phdfbk/phdfbk.github.io#32]
Per alcuni studenti non viene visualizzata l'icona di default in assenza della foto. Ad es.: Prashant Mathur.

**Comment by napo** [comment]
l'immagine sostitutiva e' prevista qualora il nome dell'immagine non sia presente nel foglio di calcolo.
Se pero' e' presente il nome del file, ma questo non e' presente sul filesystem, allora la questione diventa leggermente complessa.
Si puo' comunque scrivere la procedura di verifica.
Credo pero' che sarebbe piu' semplice risolverla chiedendo di inserire l'immagine o levare la voce dal foglio di calcolo.

**Comment by gaetanocalabrese** [comment]
Ci sono dei problemi con quelle immagini..prima erano nella cartella img
le ho spostate in img /students...ma non sono visualizzate..
Gaetano

2016-09-23 10:43 GMT+02:00 Maurizio Napolitano notifications@github.com:

**Comment by napo** [comment]
great!
mi confermi: problema di filesystem
