### ISSUE TITLE
Former students

### ISSUE THREAD

**Issue by paolo-tonella** [phdfbk/phdfbk.github.io#4]
Nell’elenco dei former students per anno, la separazione tra uno studente e il successivo andrebbe marcata meglio (ad es. con una linea o con background alternati su studenti successivi); altrimenti non si capisce se l’advisor si riferisce allo studente indicato sopra o sotto. Cambierei inoltre il colore del titolo della tesi (il grigio chiaro la mette poco in evidenza).

**Comment by napo** [comment]
- ora ogni studente ha un suo box colorato con angoli tondi
- ogni box e' separato da un altro con una riga vuota di diverso colore
- il titolo della tesi ora appare con testo in corsivo
- e' stata abilitata la vista "all"
