### ISSUE TITLE
Universita' - dipartimenti

### ISSUE THREAD

**Issue by paolo-tonella** [phdfbk/phdfbk.github.io#5]
Ci vorrebbe un mccanismo (es. id) per poter controllare l’ordine con cui vengono mostrate le universita’ in Network e i dipartimenti nella finestra modale di ciascuna universita’.

**Comment by napo** [comment]
Ho aggiunto nei file __aff_.md_ che si trovano in  _affiliations/_posts_ la variabile _order_ 

Adesso la pagina affiliations_grid.html viene generata ordinando per _order_ 

Come sequenza ho preso i numeri dopo la parola "aff" nei file creati
