### ISSUE TITLE
URL in open calls

### ISSUE THREAD

**Issue by paolo-tonella** [phdfbk/phdfbk.github.io#6]
In Open Calls, gli URL che puntano ai topic FBK dovrebbero essere cliccabili. Ad es.:

REASONING-BASED PROCESS MINING
URL: /opencalls/2016/06/01/genova-call1/
Advisor: Chiara Ghidini

**Comment by napo** [comment]
vorresti che puntassero su una url tipo questa?
http://phd.fbk.eu/opencalls/2016/06/01/genova-call1/

**Comment by paolo-tonella** [comment]
Se l'attributo Url e' specificato, come nella call #1 di UNIGE, dovrebbe apparire un link esterno cliccabile. Nel caso della call #1 di UNIGE dovrebbe apparire l'attributo URL:

http://phd.dibris.unige.it/csse/index.php/how-to-apply/themes/research-projects#ghidini

anziche':

/opencalls/2016/06/01/genova-call1/

Nel caso della call #1 di UNITN, in cui URL e' vuoto, dovrebbe rimanere vuoto anziché' apparire:

/opencalls/2016/06/01/trento-call1/

**Comment by napo** [comment]
Ho risolto cambiando il la variabile nel markdown delle singole call da "url" a "applyurl".
Ora sono mostrati i link quando presenti.
Do per scontato che le url dove si applica sono tutte su siti remoti a phd.fbk.eu
Giusto?

PS:
il laytout convince?

**Comment by paolo-tonella** [comment]
Si', sono tutti siti remoti. Il layout mi sembra OK. Puoi chiudere l'issue.
