### ISSUE TITLE
Dimensioni loghi universita'

### ISSUE THREAD

**Issue by paolo-tonella** [phdfbk/phdfbk.github.io#7]
I loghi delle universita' affiliate dovrebbero avere tutti la stessa altezza. Ho provato a ridimensionare (dopo aver fatto crop) il logo di UNITN, ma appare ancora diverso da quello di UNIPD.

**Comment by napo** [comment]
dato che volevo risolvere questa issue mi sono messo a cercare i loghi delle università e caricali sostituendo anche i precedenti.

**Comment by napo** [comment]
Ho messo i loghi con risoluzione molto alta (circa 1.000 pixel di larghezza).
Ci pensa il browser poi a gestirli a e scalarli grazie a bootstrap usand img-responsive
